const boardMembers = [
   {
      name: "Pr. John Doe",
      role: "Church Pastor",
      dept: "Administration",
      email: "pastor@mutsda.org",
      phone: "+254 700 100 001",
      quote: "The greatest want of the world is the want of men - men who will not be bought or sold; men who in their inmost souls are true and honest.",
      image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=800",
   },
   {
      name: "Elder Jane Smith",
      role: "First Elder",
      dept: "Administration",
      email: "elder1@mutsda.org",
      phone: "+254 700 100 002",
      quote: "God never leads His children otherwise than they would choose to be led, if they could see the end from the beginning.",
      image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=800",
   },
   {
      name: "David Mwangi",
      role: "Youth Director",
      dept: "Youth Ministries",
      email: "youth@mutsda.org",
      phone: "+254 700 100 003",
      quote: "With such an army of workers as our youth, rightly trained, how soon the message of a crucified Saviour might be carried to the whole world!",
      image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=800",
   },
   {
      name: "Alice Johnson",
      role: "Music Director",
      dept: "Music",
      email: "music@mutsda.org",
      phone: "+254 700 100 004",
      quote: "Music was made to serve a holy purpose, to lift the thoughts to that which is pure, noble, and elevating.",
      image: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?q=80&w=800",
   },
   {
      name: "James Omondi",
      role: "Sabbath School Supt.",
      dept: "Sabbath School",
      email: "ss@mutsda.org",
      phone: "+254 700 100 005",
      quote: "The Sabbath school is an important branch of the missionary work, not only because it gives to young and old a knowledge of God's word.",
      image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=800",
   },
   {
      name: "Dr. Peter Kamau",
      role: "Health Secretary",
      dept: "Health Ministries",
      email: "health@mutsda.org",
      phone: "+254 700 100 006",
      quote: "The right hand of the gospel is the medical missionary work, used to break down prejudice and open the way for the truth.",
      image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=800",
   },
   {
      name: "Martha White",
      role: "Children's Leader",
      dept: "Children Ministries",
      email: "kids@mutsda.org",
      phone: "+254 700 100 007",
      quote: "While the shepherds are looking after the lost sheep, the lambs should be looked after with equal care.",
      image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=800",
   },
   {
      name: "Thomas Bell",
      role: "Head Deacon",
      dept: "Deaconry",
      email: "deacons@mutsda.org",
      phone: "+254 700 100 008",
      quote: "The deacons are to be men of honest report, full of the Holy Ghost and wisdom, whom we may appoint over this business.",
      image: "https://images.unsplash.com/photo-1463453091185-61582044d556?q=80&w=800",
   },
   {
      name: "Lucy Gray",
      role: "Welfare Leader",
      dept: "Community Services",
      email: "welfare@mutsda.org",
      phone: "+254 700 100 009",
      quote: "True religion is to visit the fatherless and widows in their affliction, and to keep oneself unspotted from the world.",
      image: "https://images.unsplash.com/photo-1554151228-14d9def656e4?q=80&w=800",
   },
];

export default boardMembers;
